<?php return array (
  6255146 => 
  array (
    'geonameid' => '6255146',
    'name' => 'Africa',
    'asciiname' => 'Africa',
    'alternatenames' => 'Aafrika,Affrica,Africa,Afrihkka,Afrihkká,Afrika,Afrikka,Afriko,Afrique,Afryka,Afríka,Afrîka,Aphrike,Chau Phi,Châu Phi,afrika,afryqa,afryqya,afurika,an Afraic,apeulika,el Continente Negro,fei zhou,Àfrica,África,Āfrika,Αφρική,Африка,אפריקה,أفريقيا,افریقا,अफ़्रीका,แอฟริกา,アフリカ,非洲,아프리카',
    'latitude' => '7.1881',
    'longitude' => '21.09375',
    'feature class' => 'L',
    'feature code' => 'CONT',
    'country code' => NULL,
    'cc2' => 'AO,BF,BI,BJ,BW,CD,CF,CG,CI,CM,CV,DJ,DZ,EG,ER,ET,GA,GH,GM,GN,GQ,GW,KE,KM,LR,LS,LY,MA,MG,ML,MR,MU,MW,MZ,NA,NE,NG,RE,RW,SC,SD,SH,SL,SN,SO,SS,ST,SZ,TD,TG,TN,TZ,UG,YT,ZA,ZM,ZW',
    'admin1 code' => NULL,
    'admin2 code' => NULL,
    'admin3 code' => NULL,
    'admin4 code' => NULL,
    'population' => '1031833000',
    'elevation' => NULL,
    'dem' => '592',
    'timezone' => 'Africa/Bangui',
    'modification date' => '2019-08-12',
  ),
  6255147 => 
  array (
    'geonameid' => '6255147',
    'name' => 'Asia',
    'asciiname' => 'Asia',
    'alternatenames' => 'Aasia,Asia,Asie,Asien,Asya,Asía,Azia,Azie,Azija,Azio,Azië,Azja,Azsia,Chau A,Châu Á,ajia,an Aise,an Áise,asia,asya,ayshya,esiya mahadvipa,xecheiy,ya zhou,Àsia,Ásia,Ázia,Ázsia,Āzija,Ασία,Азия,Азія,אסיה,آسيا,ایشیا,एशिया महाद्वीप,เอเชีย,アジア,亚洲,아시아',
    'latitude' => '29.84064',
    'longitude' => '89.29688',
    'feature class' => 'L',
    'feature code' => 'CONT',
    'country code' => NULL,
    'cc2' => 'AE,AF,AM,AZ,BD,BH,BN,BT,CN,CY,GE,HK,ID,IL,IN,IQ,IR,JO,JP,KG,KH,KP,KR,KW,KZ,LA,LB,LK,MM,MN,MO,MV,MY,NP,OM,PH,PK,PS,QA,SA,SG,SY,TH,TJ,TL,TM,TR,TW,UZ,VN,YE',
    'admin1 code' => NULL,
    'admin2 code' => NULL,
    'admin3 code' => NULL,
    'admin4 code' => NULL,
    'population' => '3812366000',
    'elevation' => NULL,
    'dem' => '5101',
    'timezone' => 'Australia/Perth',
    'modification date' => '2019-08-12',
  ),
  6255148 => 
  array (
    'geonameid' => '6255148',
    'name' => 'Europe',
    'asciiname' => 'Europe',
    'alternatenames' => 'Avrupa,Chau Au,Châu Âu,Eiropa,El viejo continente,Eropa,Eurohpa,Eurohpá,Euroopa,Eurooppa,Europa,Europe,Europo,Európa,Evropa,Evrópa,Ewrop,Ewropa,Eŭropo,Rashka,an Eoraip,awrwba,ou zhou,yoroppa,yuleob,yurop,yuropa,Ευρώπη,Європа,Европа,Еўропа,Рашка,אירופה,أوروبا,यूरोप,ยุโรป,ヨーロッパ,欧洲,유럽',
    'latitude' => '48.69096',
    'longitude' => '9.14062',
    'feature class' => 'L',
    'feature code' => 'CONT',
    'country code' => NULL,
    'cc2' => 'AD,AL,AT,AX,BA,BE,BG,BY,CH,CZ,DE,DK,EE,ES,FI,FO,FR,GB,GG,GI,GR,HR,HU,IE,IM,IS,IT,JE,LI,LT,LU,LV,MC,MD,ME,MK,MT,NL,NO,PL,PT,RO,RS,RU,SE,SI,SJ,SK,SM,UA,VA',
    'admin1 code' => NULL,
    'admin2 code' => NULL,
    'admin3 code' => NULL,
    'admin4 code' => NULL,
    'population' => '741000000',
    'elevation' => NULL,
    'dem' => '443',
    'timezone' => 'Europe/Vaduz',
    'modification date' => '2019-08-12',
  ),
  6255149 => 
  array (
    'geonameid' => '6255149',
    'name' => 'North America',
    'asciiname' => 'North America',
    'alternatenames' => 'Abya Yala,America Septentrional,America del Nord,America del Norte,America do Norte,America settentrionale,Amerika Utara,Amerikaya Bakur,Amerique du Nord,Ameryka Polnocna,Ameryka Północna,Amerîkaya Bakur,Amèrica del Nord,América Septentrional,América del Norte,América do Norte,Amérique du Nord,Bac My,Boreia Amerike,Bắc Mỹ,Davvi-Amerihkka,Davvi-Amerihkká,Eszak-Amerika,Gogledd America,Kuzey Amerika,Meiricea Thuaidh,Meiriceá Thuaidh,Noord-Amerika,Nord-Amerika,Nordamerika,Nordameriko,Nordur-Amerika,Norteamerica,Norteamérica,North America,Norður-Ameríka,Pivnichna Amerika,Pohja-Ameerika,Pohjois-Amerikka,Põhja-Ameerika,Severna Amerika,Severnaja Amerika,Severni Amerika,Severná Amerika,Severní Amerika,Siaures Amerika,Sjeverna Amerika,Ziemelamerika,Ziemeļamerika,amryka alshmalyt,bei mei zhou,beiamerika,bug-amelika,uttari amarika,xmerikahenux,Észak-Amerika,Šiaurės Amerika,Βόρεια Αμερική,Північна Америка,Северна Америка,Северная Америка,אמריקה הצפונית,أمريكا الشمالية,شمالی امریکہ,उत्तरी अमरीका,อเมริกาเหนือ,北アメリカ,北美洲,북아메리카',
    'latitude' => '46.07323',
    'longitude' => '-100.54688',
    'feature class' => 'L',
    'feature code' => 'CONT',
    'country code' => NULL,
    'cc2' => 'AG,AI,AW,BB,BL,BM,BQ,BS,BZ,CA,CR,CU,CW,DM,DO,GD,GL,GP,GT,HN,HT,JM,KN,KY,LC,MF,MQ,MS,MX,NI,PA,PM,PR,SV,SX,TC,TT,US,VC,VG,VI',
    'admin1 code' => NULL,
    'admin2 code' => NULL,
    'admin3 code' => NULL,
    'admin4 code' => NULL,
    'population' => '580000000',
    'elevation' => NULL,
    'dem' => '570',
    'timezone' => 'America/Cambridge_Bay',
    'modification date' => '2019-08-12',
  ),
  6255150 => 
  array (
    'geonameid' => '6255150',
    'name' => 'South America',
    'asciiname' => 'South America',
    'alternatenames' => 'Abya Yala,America Meridional,America del Sud,America del Sur,America do Sul,America meridionale,Amerika Selatan,Amerikaya Basur,Amerique du Sud,Ameryka Poludniowa,Ameryka Południowa,Amerîkaya Başûr,Amèrica del Sud,América Meridional,América del Sud,América del Sur,América do Sul,Amérique du Sud,De America,Del-Amerika,Dienvidamerika,Dél-Amerika,Etelae-Amerikka,Etelä-Amerikka,Gueney Amerika,Güney Amerika,Hego-Amerika,Hegoamerika,Jizni Amerika,Jižní Amerika,Juzhna Amerika,Juzhnaja Amerika,Juzna Amerika,Južna Amerika,Južná Amerika,Louna-Ameerika,Lulli-Amerihkka,Lulli-Amerihkká,Lõuna-Ameerika,Meiricea Theas,Meiriceá Theas,Nam My,Nam Mỹ,Notia Amerike,Pietu Amerika,Pietų Amerika,Pivdenna Amerika,Sor-Amerika,South America,Sudamerica,Sudameriko,Sudamérica,Sudur-Amerika,Suedamerika,Suramerica,Suramérica,Suður-Ameríka,Sydamerika,Sør-Amerika,Südamerika,Zuid-Amerika,amryka aljnwbyt,daksini amarika,nam-amelika,nan mei zhou,nanamerika,Νότια Αμερική,Південна Америка,Южна Америка,Южная Америка,אמריקה הדרומית,أمريكا الجنوبية,दक्षिणी अमरीका,อเมริกาใต้,南アメリカ,南美洲,남아메리카',
    'latitude' => '-14.60485',
    'longitude' => '-57.65625',
    'feature class' => 'L',
    'feature code' => 'CONT',
    'country code' => NULL,
    'cc2' => 'BR,CO,AR,PE,VE,CL,EC,BO,PY,UY,GY,SR,GF,FK',
    'admin1 code' => NULL,
    'admin2 code' => NULL,
    'admin3 code' => NULL,
    'admin4 code' => NULL,
    'population' => '385742554',
    'elevation' => NULL,
    'dem' => '278',
    'timezone' => 'America/Recife',
    'modification date' => '2019-08-12',
  ),
  6255151 => 
  array (
    'geonameid' => '6255151',
    'name' => 'Oceania',
    'asciiname' => 'Oceania',
    'alternatenames' => 'Chau GJai Duong,Châu Đại Dương,Eyjaalfa,Eyjaálfa,Oceania,Oceanie,Oceanien,Oceanio,Oceanië,Oceanía,Oceánia,Oceánie,Océanie,Okeaania,Okeania,Okeanija,Okeānija,Okyanusya,Oseania,Ozeanien,an Aigeine,an Aigéine,awqyanwsya,da yang zhou,oseania,osiniya,xo cheiy neiy,Óceánia,Ωκεανία,Океания,Океанія,אוקיאניה,أوقيانوسيا,ओशीनिया,โอเชียเนีย,オセアニア,大洋洲,오세아니아',
    'latitude' => '-18.31281',
    'longitude' => '138.51562',
    'feature class' => 'L',
    'feature code' => 'CONT',
    'country code' => NULL,
    'cc2' => 'AU,CK,FJ,FM,GU,KI,MH,NC,NF,NR,NU,NZ,PG,PN,PW,SB,TK,TO,TV,VU,WF,WS',
    'admin1 code' => NULL,
    'admin2 code' => NULL,
    'admin3 code' => NULL,
    'admin4 code' => NULL,
    'population' => '40000000',
    'elevation' => NULL,
    'dem' => '72',
    'timezone' => 'Pacific/Pohnpei',
    'modification date' => '2019-08-12',
  ),
  6255152 => 
  array (
    'geonameid' => '6255152',
    'name' => 'Antarctica',
    'asciiname' => 'Antarctica',
    'alternatenames' => '\'Anetatika,Antarctica,Antarctique,Antarktida,Antarktik,Antarktika,Antarktike,Antarktis,Antarktisz,Antarkto,Antarktyda,Antarktyka,Antarktída,Antarktíka,Antarktîka,Antarktīda,Antartica,Antartida,Antartide,Antartika,Antàrtida,Antárktis,Antártica,Antártida,Chau Nam Cuc,Châu Nam Cực,Etelaemanner,Etelämanner,Nam Cuc,Nam Cực,Sudurheimskautslandid,Sudurskautslandid,Suðurheimskautslandið,Suðurskautslandið,alqtb aljnwby,an Antartaice,antarkatika,antarktyka,namgeug,nan ji,nan ji da lu,nan ji zhou,qtb jnwb,ʻAnetātika,Ανταρκτική,Антарктида,Антарктик,Антарктика,Антарктыка,אנטארקטיקה,אנטרקטיקה,أنتاركتيكا,القطب الجنوبي,انتارکتیکا,انٹار ٹکا,قطب جنوب,अंटार्कटिका,আন্টার্কটিকা,അന്‍റാര്‍ട്ടിക്ക,แอนตาร์กติกา,ལྷོ་རྩེའི་མཐའ་གླིང་།,ཨེན་ཊཱག་ཊི་ཀ,ანტარქტიკა,አንታርክቲካ,南极洲,南極,南極大陸,남극',
    'latitude' => '-78.15856',
    'longitude' => '16.40626',
    'feature class' => 'L',
    'feature code' => 'CONT',
    'country code' => NULL,
    'cc2' => NULL,
    'admin1 code' => NULL,
    'admin2 code' => NULL,
    'admin3 code' => NULL,
    'admin4 code' => NULL,
    'population' => '1100',
    'elevation' => NULL,
    'dem' => '3199',
    'timezone' => 'Antarctica/Syowa',
    'modification date' => '2018-12-10',
  ),
);
