name: PHPUnit

on:
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        include:
          - php: 7.3
            dependencies: laravel/framework:^8.0
            prefer_lowest: 0

          - php: 8.0
            dependencies: laravel/framework:^9.0
            prefer_lowest: 0

          - php: 8.1
            dependencies: laravel/framework:^10.0
            prefer_lowest: 0

          - php: 8.2
            dependencies: laravel/framework:^11.0
            prefer_lowest: 0

          - php: 8.2
            dependencies: laravel/framework:^12.0
            prefer_lowest: 0

    runs-on: ubuntu-latest

    env:
      COMPOSER_PREFER_STABLE: 1
      COMPOSER_PREFER_LOWEST: ${{ matrix.prefer_lowest }}

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - run: composer require ${{ matrix.dependencies }} --no-update --no-interaction --no-progress

      - run: composer update --no-interaction --no-progress

      - run: vendor/bin/phpunit

  coverage:
    name: Analyze code coverage

    runs-on: ubuntu-latest

    env:
      PHP_VERSION: 7.3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build containers
        run: docker compose build

      - name: Install Composer dependencies
        run: docker compose run composer update --no-interaction --no-progress

      - name: Run PHPUnit with a coverage analysis
        run: docker compose run phpunit --coverage-clover coverage.xml

      - name: Upload the coverage report
        uses: codecov/codecov-action@v3
